# **Import Library**

In [ ]:
import geopandas as gpd
import pandas as pd
from scipy import sparse
import numpy as np
import matplotlib.pyplot as plt
from libpysal.weights import Queen, WSP, W
from numpy import sqrt
import statsmodels.api as sm
!pip install esda splot libpysal geopandas
from esda.moran import Moran
from statsmodels.stats.outliers_influence import variance_inflation_factor
from operator import itemgetter
from scipy.stats import kstest, norm

Requirement already satisfied: esda in /usr/local/lib/python3.12/dist-packages (2.8.0)
Requirement already satisfied: splot in /usr/local/lib/python3.12/dist-packages (1.1.7)
Requirement already satisfied: libpysal in /usr/local/lib/python3.12/dist-packages (4.13.0)
Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (1.1.1)
Requirement already satisfied: numpy>=1.26 in /usr/local/lib/python3.12/dist-packages (from esda) (2.0.2)
Requirement already satisfied: pandas>=2.1 in /usr/local/lib/python3.12/dist-packages (from esda) (2.2.2)
Requirement already satisfied: scikit-learn>=1.4 in /usr/local/lib/python3.12/dist-packages (from esda) (1.6.1)
Requirement already satisfied: scipy>=1.12 in /usr/local/lib/python3.12/dist-packages (from esda) (1.16.3)
Requirement already satisfied: shapely>=2.1 in /usr/local/lib/python3.12/dist-packages (from esda) (2.1.2)
Requirement already satisfied: giddy in /usr/local/lib/python3.12/dist-packages (from splot) (2.3.6)
Requirement already satisfied: mapclassify in /usr/local/lib/python3.12/dist-packages (from splot) (2.10.0)
Requirement already satisfied: matplotlib>=3.3.3 in /usr/local/lib/python3.12/dist-packages (from splot) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from splot) (25.0)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from splot) (0.13.2)
Requirement already satisfied: spreg in /usr/local/lib/python3.12/dist-packages (from splot) (1.8.3)
Requirement already satisfied: beautifulsoup4>=4.10 in /usr/local/lib/python3.12/dist-packages (from libpysal) (4.13.5)
Requirement already satisfied: platformdirs>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from libpysal) (4.5.0)
Requirement already satisfied: requests>=2.27 in /usr/local/lib/python3.12/dist-packages (from libpysal) (2.32.4)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas) (0.11.1)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (3.7.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.10->libpysal) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.10->libpysal) (4.15.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.3->splot) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.3->splot) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.3->splot) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.3->splot) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.3->splot) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.3->splot) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3.3->splot) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1->esda) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.1->esda) (2025.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyogrio>=0.7.2->geopandas) (2025.10.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.27->libpysal) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.27->libpysal) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.27->libpysal) (2.5.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4->esda) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4->esda) (3.6.0)
Requirement already satisfied: quantecon>=0.7 in /usr/local/lib/python3.12/dist-packages (from giddy->splot) (0.10.1)
Requirement already satisfied: networkx>=3.2 in /usr/local/lib/python3.12/dist-packages (from mapclassify->splot) (3.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.3->splot) (1.17.0)
Requirement already satisfied: numba>=0.49.0 in /usr/local/lib/python3.12/dist-packages (from quantecon>=0.7->giddy->splot) (0.60.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from quantecon>=0.7->giddy->splot) (1.13.3)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.49.0->quantecon>=0.7->giddy->splot) (0.43.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->quantecon>=0.7->giddy->splot) (1.3.0)

# **Load Data**

In [ ]:
gdf = gpd.read_file("Jawa Tengah.zip")

In [ ]:
spasial_df = pd.read_excel("Spasial_Jawa_Tengah_Cleaned.xlsx")
spasial_df = spasial_df.drop(columns = ["Latitude","Longitude"])

# **Statistika Deskriptif**

In [ ]:
gdf.head()

,NAMOBJ,FCODE,REMARK,METADATA,SRS_ID,KDBBPS,KDCBPS,KDCPUM,KDEBPS,KDEPUM,...,WADMKD,WADMKK,WADMPR,WIADKC,WIADKK,WIADPR,WIADKD,SHAPE_Leng,SHAPE_Area,geometry
0,Banjarnegara,BA03050040,None,TASWIL5000020230907KABKOTA,4326,None,None,None,None,None,...,None,Banjarnegara,Jawa Tengah,None,None,None,0,2.297379,0.093763,"POLYGON Z ((109.91691 -7.18985 0, 109.91746 -7..."
1,Banyumas,BA03050040,None,TASWIL5000020230907KABKOTA,4326,None,None,None,None,None,...,None,Banyumas,Jawa Tengah,None,None,None,0,2.197132,0.113957,"POLYGON Z ((109.3617 -7.48538 0, 109.36152 -7...."
2,Batang,BA03050040,None,TASWIL5000020230907KABKOTA,4326,None,None,None,None,None,...,None,Batang,Jawa Tengah,None,None,None,0,1.531137,0.070157,"POLYGON Z ((109.71086 -6.86701 0, 109.71113 -6..."
3,Blora,BA03050040,None,TASWIL5000020230907KABKOTA,4326,None,None,None,None,None,...,None,Blora,Jawa Tengah,None,None,None,0,2.588665,0.160200,"POLYGON Z ((111.26338 -6.85576 0, 111.26338 -6..."
4,Boyolali,BA03050040,None,TASWIL5000020230907KABKOTA,4326,None,None,None,None,None,...,None,Boyolali,Jawa Tengah,None,None,None,0,3.034328,0.089820,"POLYGON Z ((110.83881 -7.26261 0, 110.83741 -7..."

In [ ]:
gdf.describe()

            LUASWH     TIPADM  WIADKD  SHAPE_Leng  SHAPE_Area
count    35.000000  35.000000    35.0   35.000000   35.000000
mean    981.071558   4.171429     0.0    1.953899    0.080331
std     582.048388   0.382385     0.0    0.951163    0.047666
min      18.558259   4.000000     0.0    0.270626    0.001520
25%     752.266064   4.000000     0.0    1.562397    0.061649
50%    1008.124240   4.000000     0.0    1.916551    0.082506
75%    1141.154380   4.000000     0.0    2.541063    0.093425
max    2323.926116   5.000000     0.0    4.838730    0.190380

In [ ]:
spasial_df.head()

       Kab/Kota      Y    RLS     AHH   TPT      APD
0  Banjarnegara  14.71  6.910  74.875  5.57  2352.02
1      Banyumas  11.95  7.925  74.440  6.18  3852.98
2        Batang   8.73  7.175  75.295  5.67  1943.91
3         Blora  11.42  7.330  75.145  3.67  2624.07
4      Boyolali   9.63  8.215  76.650  3.16  2354.35

In [ ]:
spasial_df.describe()

               Y        RLS        AHH        TPT          APD
count  35.000000  35.000000  35.000000  35.000000    35.000000
mean   10.128571   8.359143  75.644429   4.519714  2476.441429
std     3.211398   1.383067   1.828924   1.494546   814.954276
min     4.030000   6.420000  70.340000   2.350000   983.640000
25%     7.555000   7.397500  74.670000   3.500000  2118.945000
50%     9.630000   7.925000  75.470000   3.970000  2403.010000
75%    11.995000   9.250000  76.830000   5.320000  2782.595000
max    15.710000  11.550000  78.375000   8.350000  5231.590000

# **WEIGHT MATRIX**

In [ ]:
gdf["centroid"] = gdf.geometry.centroid
gdf["centroid_lon"] = gdf.centroid.x
gdf["centroid_lat"] = gdf.centroid.y
print(gdf[["centroid", "centroid_lon", "centroid_lat"]])

                      centroid  centroid_lon  centroid_lat
0   POINT (109.65705 -7.35133)    109.657052     -7.351327
1   POINT (109.17579 -7.45551)    109.175788     -7.455509
2     POINT (109.86159 -7.021)    109.861593     -7.021002
3   POINT (111.38744 -7.07444)    111.387435     -7.074438
4    POINT (110.6525 -7.41652)    110.652499     -7.416522
5   POINT (108.92953 -7.06277)    108.929526     -7.062772
6   POINT (108.88984 -7.48893)    108.889839     -7.488927
7     POINT (110.634 -6.91077)    110.634005     -6.910774
8   POINT (110.92718 -7.11764)    110.927178     -7.117637
9     POINT (110.76813 -6.549)    110.768129     -6.549003
10  POINT (111.01924 -7.61414)    111.019242     -7.614139
11  POINT (109.61735 -7.65496)    109.617353     -7.654964
12  POINT (110.15734 -7.03869)    110.157338     -7.038695
13  POINT (110.61945 -7.68582)    110.619452     -7.685818
14  POINT (110.22011 -7.47655)    110.220111     -7.476555
15  POINT (109.67716 -6.89341)    109.677155     -6.893409
16  POINT (110.49837 -7.33768)    110.498374     -7.337678
17   POINT (110.39152 -7.0239)    110.391523     -7.023899
18  POINT (110.82314 -7.55789)    110.823145     -7.557894
19  POINT (109.11575 -6.86917)    109.115747     -6.869175
20  POINT (110.86991 -6.79026)    110.869907     -6.790261
21  POINT (110.24721 -7.50174)    110.247213     -7.501737
22  POINT (111.04228 -6.74333)    111.042283     -6.743327
23   POINT (109.6205 -7.05701)    109.620501     -7.057006
24   POINT (109.39517 -7.0368)    109.395173     -7.036804
25   POINT (109.4072 -7.32323)    109.407205     -7.323230
26  POINT (109.96613 -7.70038)    109.966126     -7.700381
27  POINT (111.46152 -6.77513)    111.461520     -6.775134
28   POINT (110.47351 -7.2709)    110.473508     -7.270899
29  POINT (110.97414 -7.38534)    110.974144     -7.385337
30  POINT (110.83484 -7.68084)    110.834837     -7.680844
31  POINT (109.15852 -7.02878)    109.158515     -7.028775
32    POINT (110.1363 -7.2577)    110.136302     -7.257698
33  POINT (110.99921 -7.91929)    110.999213     -7.919285
34   POINT (109.90735 -7.4163)    109.907355     -7.416302

/tmp/ipython-input-1311769737.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf["centroid"] = gdf.geometry.centroid
/tmp/ipython-input-1311769737.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf["centroid_lon"] = gdf.centroid.x
/tmp/ipython-input-1311769737.py:3: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf["centroid_lat"] = gdf.centroid.y

## Memilih kolom yang akan dipakai pada gdf

In [ ]:
df = pd.DataFrame(gdf[["NAMOBJ","centroid", "centroid_lon", "centroid_lat"]])

In [ ]:
df["Index"] = df.index

In [ ]:
df = df[["Index",'NAMOBJ',"centroid", "centroid_lon", "centroid_lat"]]

In [ ]:
df

,Index,NAMOBJ,centroid,centroid_lon,centroid_lat
0,0,Banjarnegara,POINT (109.65705 -7.35133),109.657052,-7.351327
1,1,Banyumas,POINT (109.17579 -7.45551),109.175788,-7.455509
2,2,Batang,POINT (109.86159 -7.021),109.861593,-7.021002
3,3,Blora,POINT (111.38744 -7.07444),111.387435,-7.074438
4,4,Boyolali,POINT (110.6525 -7.41652),110.652499,-7.416522
5,5,Brebes,POINT (108.92953 -7.06277),108.929526,-7.062772
6,6,Cilacap,POINT (108.88984 -7.48893),108.889839,-7.488927
7,7,Demak,POINT (110.634 -6.91077),110.634005,-6.910774
8,8,Grobogan,POINT (110.92718 -7.11764),110.927178,-7.117637
9,9,Jepara,POINT (110.76813 -6.549),110.768129,-6.549003
10,10,Karanganyar,POINT (111.01924 -7.61414),111.019242,-7.614139
11,11,Kebumen,POINT (109.61735 -7.65496),109.617353,-7.654964
12,12,Kendal,POINT (110.15734 -7.03869),110.157338,-7.038695
13,13,Klaten,POINT (110.61945 -7.68582),110.619452,-7.685818
14,14,Kota Magelang,POINT (110.22011 -7.47655),110.220111,-7.476555
15,15,Kota Pekalongan,POINT (109.67716 -6.89341),109.677155,-6.893409
16,16,Kota Salatiga,POINT (110.49837 -7.33768),110.498374,-7.337678
17,17,Kota Semarang,POINT (110.39152 -7.0239),110.391523,-7.023899
18,18,Kota Surakarta,POINT (110.82314 -7.55789),110.823145,-7.557894
19,19,Kota Tegal,POINT (109.11575 -6.86917),109.115747,-6.869175
20,20,Kudus,POINT (110.86991 -6.79026),110.869907,-6.790261
21,21,Magelang,POINT (110.24721 -7.50174),110.247213,-7.501737
22,22,Pati,POINT (111.04228 -6.74333),111.042283,-6.743327
23,23,Pekalongan,POINT (109.6205 -7.05701),109.620501,-7.057006
24,24,Pemalang,POINT (109.39517 -7.0368),109.395173,-7.036804
25,25,Purbalingga,POINT (109.4072 -7.32323),109.407205,-7.323230
26,26,Purworejo,POINT (109.96613 -7.70038),109.966126,-7.700381
27,27,Rembang,POINT (111.46152 -6.77513),111.461520,-6.775134
28,28,Semarang,POINT (110.47351 -7.2709),110.473508,-7.270899
29,29,Sragen,POINT (110.97414 -7.38534),110.974144,-7.385337
30,30,Sukoharjo,POINT (110.83484 -7.68084),110.834837,-7.680844
31,31,Tegal,POINT (109.15852 -7.02878),109.158515,-7.028775
32,32,Temanggung,POINT (110.1363 -7.2577),110.136302,-7.257698
33,33,Wonogiri,POINT (110.99921 -7.91929),110.999213,-7.919285
34,34,Wonosobo,POINT (109.90735 -7.4163),109.907355,-7.416302

## Menghitung jarak dengan jarak Haversine

Karena ini adalah data spasial yang cukup besar, lebih akurat apabila menggunakan jarak Haversine

In [ ]:
def haversine(lon1, lat1, lon2, lat2):
    R = 6371  # Jari-jari bumi dalam km
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat/2)**2 + np.cos(lat1)*np.cos(lat2)*np.sin(dlon/2)**2
    return 2 * R * np.arcsin(np.sqrt(a))

Distance Matrix tanpa standardisasi dan neighbor

In [ ]:
coords = df[['centroid_lon', "centroid_lat"]].to_numpy()
n = len(coords)
dist = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        dist[i, j] = haversine(coords[i,0], coords[i,1], coords[j,0], coords[j,1])

In [ ]:
w = Queen.from_dataframe(gdf)

/tmp/ipython-input-38079147.py:1: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(gdf)

In [ ]:
yesyes = np.zeros((35,35))
yes = w.neighbors
for i in yes:
  for j in yes[i]:
    yesyes[i][j] = dist[i][j]

## Standardisasi Baris Bobot Matriks

In [ ]:
def standard(array):
  for i,j in enumerate(array):
    array[i] = j/sum(j)
  return array

In [ ]:
final = standard(yesyes)

In [ ]:
final

array([[0.        , 0.24610604, 0.19531803, ..., 0.        , 0.        ,
        0.12927293],
       [0.16953397, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.25096599, 0.        , 0.        , ..., 0.        , 0.        ,
        0.25758005],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.25193321],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.10715765, 0.        , 0.16617102, ..., 0.11567232, 0.        ,
        0.        ]])

In [ ]:
for i in final:
  print(sum(i))

1.0
0.9999999999999998
1.0
1.0
0.9999999999999997
1.0
1.0
1.0
1.0000000000000002
0.9999999999999999
1.0
1.0
0.9999999999999999
1.0
1.0
1.0
1.0
1.0
1.0
0.9999999999999999
1.0
0.9999999999999999
1.0
1.0
1.0
1.0
1.0000000000000002
1.0
0.9999999999999997
1.0
1.0
1.0
0.9999999999999999
1.0
1.0000000000000002

# **Uji Moran**

$I = \frac{n}{W} \cdot \frac{\sum_i \sum_j w_{ij} (x_i - \bar{x})(x_j - \bar{x})}{\sum_i (x_i - \bar{x})^2}$

In [ ]:
W_array = final.copy().astype(float)
y = spasial_df['Y'].values

neighbors = {i: np.where(W_array[i] > 0)[0].tolist() for i in range(W_array.shape[0])}
weights = {i: W_array[i, W_array[i] > 0].tolist() for i in range(W_array.shape[0])}

w = W(neighbors, weights)
w.transform = "R"

moran = Moran(y, w, permutations=999)

print("Moran’s I:", moran.I)
print("Expected I:", moran.EI)
print("Z-score:", moran.z_sim)
print("P-value:", moran.p_sim)

Moran’s I: 0.15535806091745252
Expected I: -0.029411764705882353
Z-score: 1.546741541284157
P-value: 0.07

# **SPATIAL LAG X MODEL**

In [ ]:
spasial_df

           Kab/Kota      Y     RLS     AHH   TPT      APD
0      Banjarnegara  14.71   6.910  74.875  5.57  2352.02
1          Banyumas  11.95   7.925  74.440  6.18  3852.98
2            Batang   8.73   7.175  75.295  5.67  1943.91
3             Blora  11.42   7.330  75.145  3.67  2624.07
4          Boyolali   9.63   8.215  76.650  3.16  2354.35
5            Brebes  15.60   6.420  70.340  8.35  3398.22
6           Cilacap  10.68   7.430  74.685  7.83  3750.29
7             Demak  11.89   8.305  75.975  4.75  2596.38
8          Grobogan  11.43   7.335  75.470  3.23  2837.80
9            Jepara   6.09   8.280  76.465  3.34  2491.75
10      Karanganyar   9.59   9.235  78.160  3.47  2353.65
11          Kebumen  15.71   7.840  74.315  5.07  3029.98
12           Kendal   9.35   7.755  75.020  5.01  2505.85
13           Klaten  12.04   9.300  77.455  3.97  2705.49
14    Kota Magelang   5.94  11.505  77.615  4.40   983.64
15  Kota Pekalongan   6.71   9.385  75.060  4.91  1005.25
16    Kota Salatiga   4.57  11.550  78.325  3.86   995.95
17    Kota Semarang   4.03  11.155  78.295  5.82  5231.59
18   Kota Surakarta   8.31  11.370  78.020  4.61  2321.48
19       Kota Tegal   7.64   9.325  75.100  5.88  1174.00
20            Kudus   7.23   9.265  77.250  3.19  2045.83
21         Magelang  10.83   7.895  74.655  3.55  2804.85
22             Pati   9.17   7.960  76.765  3.87  2853.01
23       Pekalongan   8.95   7.500  74.320  3.30  2383.99
24         Pemalang  14.92   6.620  74.295  6.63  2760.34
25      Purbalingga  14.18   7.360  73.820  4.96  2112.98
26        Purworejo  10.87   8.670  75.760  3.89  2398.99
27          Rembang  14.02   7.750  75.195  2.84  2096.12
28         Semarang   6.96   8.260  76.335  3.73  2573.50
29           Sragen  12.41   7.925  76.375  3.53  2403.01
30        Sukoharjo   7.47  10.005  78.375  3.65  2168.39
31            Tegal   6.81   7.365  72.205  7.53  2968.89
32       Temanggung   8.67   7.555  76.160  2.35  2057.40
33         Wonogiri  10.71   7.760  76.895  2.40  2414.59
34         Wonosobo  15.28   6.935  72.445  4.02  2124.91

In [ ]:
W_yes = final.copy().astype(float)

In [ ]:
y = spasial_df['Y']
X = spasial_df[['RLS', 'AHH', 'TPT', 'APD']].copy()

In [ ]:
WX_RLS = W_yes.dot(spasial_df['RLS'])
WX_AHH = W_yes.dot(spasial_df['AHH'])
WX_TPT = W_yes.dot(spasial_df['TPT'])
WX_APD = W_yes.dot(spasial_df['APD'])

In [ ]:
X.loc[:, 'WX_RLS'] = WX_RLS
X.loc[:, 'WX_AHH'] = WX_AHH
X.loc[:, 'WX_TPT'] = WX_TPT
X.loc[:, 'WX_APD'] = WX_APD

In [ ]:
X = sm.add_constant(X)

In [ ]:
model = sm.OLS(y, X).fit()

In [ ]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.555
Model:                            OLS   Adj. R-squared:                  0.418
Method:                 Least Squares   F-statistic:                     4.057
Date:                Thu, 06 Nov 2025   Prob (F-statistic):            0.00304
Time:                        08:11:03   Log-Likelihood:                -75.813
No. Observations:                  35   AIC:                             169.6
Df Residuals:                      26   BIC:                             183.6
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         21.5407     89.861      0.240      0.812    -163.171     206.252
RLS           -1.1616      0.564     -2.060      0.050      -2.321      -0.003
AHH           -0.5892      0.550     -1.071      0.294      -1.719       0.541
TPT           -0.0372      0.547     -0.068      0.946      -1.162       1.087
APD        -6.949e-05      0.001     -0.106      0.916      -0.001       0.001
WX_RLS        -0.3845      1.819     -0.211      0.834      -4.124       3.355
WX_AHH         0.5353      1.044      0.513      0.612      -1.610       2.681
WX_TPT        -0.5307      0.873     -0.608      0.549      -2.326       1.265
WX_APD         0.0031      0.002      1.667      0.107      -0.001       0.007
==============================================================================
Omnibus:                        2.404   Durbin-Watson:                   1.928
Prob(Omnibus):                  0.301   Jarque-Bera (JB):                1.372
Skew:                          -0.446   Prob(JB):                        0.503
Kurtosis:                       3.382   Cond. No.                     7.99e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.99e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
residuals = model.resid
resid_standardized = (residuals - np.mean(residuals)) / np.std(residuals)

stat, p = kstest(resid_standardized, 'norm')
print(f"KS Statistic = {stat:.3f}, p-value = {p:.3f}")

KS Statistic = 0.103, p-value = 0.818

# **VIF**

In [ ]:
vif_data = pd.DataFrame({
    "Variable": X.columns,
    "VIF": [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
})
print(vif_data)

  Variable           VIF
0    const  47114.374016
1      RLS      3.447517
2      AHH      5.732164
3      TPT      3.790036
4      APD      1.611660
5   WX_RLS      6.783859
6   WX_AHH     13.340033
7   WX_TPT      6.603824
8   WX_APD      1.957847

# **COBA2 OLS**

In [ ]:
y = spasial_df['Y']
X = spasial_df[['RLS', 'AHH', 'TPT', 'APD']].copy()
X = sm.add_constant(X)

In [ ]:
model2 = sm.OLS(y,X).fit()

In [ ]:
print(model2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.488
Model:                            OLS   Adj. R-squared:                  0.420
Method:                 Least Squares   F-statistic:                     7.160
Date:                Thu, 06 Nov 2025   Prob (F-statistic):           0.000358
Time:                        08:22:55   Log-Likelihood:                -78.261
No. Observations:                  35   AIC:                             166.5
Df Residuals:                      30   BIC:                             174.3
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         51.1982     33.741      1.517      0.140     -17.711     120.107
RLS           -1.2011      0.548     -2.191      0.036      -2.321      -0.081
AHH           -0.4068      0.483     -0.843      0.406      -1.392       0.579
TPT           -0.1658      0.422     -0.393      0.697      -1.028       0.696
APD            0.0002      0.001      0.328      0.745      -0.001       0.001
==============================================================================
Omnibus:                        0.518   Durbin-Watson:                   2.072
Prob(Omnibus):                  0.772   Jarque-Bera (JB):                0.636
Skew:                          -0.235   Prob(JB):                        0.728
Kurtosis:                       2.536   Cond. No.                     2.13e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.13e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

# **REVISI**

Terdapat revisi berdasarkan hasil uji moran yang tidak signifikan, maka dari itu akan dilakukan handling outliers

## **Handling Outliers**

In [ ]:
numeric = spasial_df.select_dtypes(include='number')
Q1 = numeric.quantile(0.25)
Q3 = numeric.quantile(0.75)
IQR = Q3 - Q1
df_no_outliers = spasial_df[~((numeric < (Q1 - 1.5 * IQR)) | (numeric > (Q3 + 1.5 * IQR))).any(axis=1)]
df_no_outliers["Index"] = df_no_outliers.index

/tmp/ipython-input-1297269212.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_outliers["Index"] = df_no_outliers.index

In [ ]:
final_df = df_no_outliers.join(df.set_index('Index'), on='Index', validate='m:1').drop(columns = ["NAMOBJ"])
final_df = final_df.reset_index(drop=True)
final_df.head()

,Kab/Kota,Y,RLS,AHH,TPT,APD,Index,centroid,centroid_lon,centroid_lat
0,Banjarnegara,14.71,6.910,74.875,5.57,2352.02,0,POINT (109.65705 -7.35133),109.657052,-7.351327
1,Batang,8.73,7.175,75.295,5.67,1943.91,2,POINT (109.86159 -7.021),109.861593,-7.021002
2,Blora,11.42,7.330,75.145,3.67,2624.07,3,POINT (111.38744 -7.07444),111.387435,-7.074438
3,Boyolali,9.63,8.215,76.650,3.16,2354.35,4,POINT (110.6525 -7.41652),110.652499,-7.416522
4,Cilacap,10.68,7.430,74.685,7.83,3750.29,6,POINT (108.88984 -7.48893),108.889839,-7.488927

## **Weight Matrix**

In [ ]:
coords = final_df[['centroid_lon', "centroid_lat"]].to_numpy()
n = len(coords)
dist = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        dist[i, j] = haversine(coords[i,0], coords[i,1], coords[j,0], coords[j,1])

In [ ]:
dist.shape

(29, 29)

In [ ]:
w = Queen.from_dataframe(gdf)

/tmp/ipython-input-38079147.py:1: FutureWarning: `use_index` defaults to False but will default to True in future. Set True/False directly to control this behavior and silence this warning
  w = Queen.from_dataframe(gdf)

In [ ]:
dict_neighbor = w.neighbors
dict_nbaru = {}
for i in dict_neighbor:
  if i in list(final_df["Index"]):
    dict_nbaru[i] = dict_neighbor[i]

final_dict = {}
for i in dict_nbaru:
  get_value = itemgetter(i)
  val = get_value(dict_nbaru)
  dummy = []
  for j in val:
    if j in list(final_df["Index"]):
      dummy.append(j)
  final_dict[i] = dummy
print(final_dict)

{0: [2, 34, 23, 25, 11], 2: [0, 34, 23, 12], 3: [8, 27, 22], 4: [8, 10, 13, 18, 21, 28, 29, 30], 6: [11], 7: [20, 8, 9, 28], 8: [3, 4, 20, 22, 7, 28, 29], 9: [20, 22, 7], 10: [33, 18, 4, 29, 30], 11: [0, 34, 6, 26], 12: [32, 2, 34, 28], 13: [4, 21, 30], 18: [10, 4, 30], 19: [31], 20: [8, 9, 22, 7], 21: [32, 34, 4, 26, 28, 13], 22: [3, 20, 8, 9, 27], 23: [0, 2, 24, 25], 24: [31, 25, 23], 25: [0, 24, 23], 26: [34, 11, 21], 27: [3, 22], 28: [32, 4, 7, 8, 12, 21], 29: [8, 10, 4], 30: [33, 18, 4, 10, 13], 31: [24, 19], 32: [34, 12, 28, 21], 33: [10, 30], 34: [0, 32, 2, 21, 26, 11, 12]}

In [ ]:
np.isnan(dist).any()

np.False_

In [ ]:
old_indices = list(df_no_outliers["Index"])
new_indices = list(range(29))

# make a mapping dictionary
mapping = dict(zip(old_indices, new_indices))

# rebuild the dictionary with new keys and remapped values
new_neighbors = {
    mapping[k]: [mapping[v] for v in vals if v in mapping]
    for k, vals in final_dict.items()
    if k in mapping
}
new_neighbors

{0: [1, 28, 17, 19, 9],
 1: [0, 28, 17, 10],
 2: [6, 21, 16],
 3: [6, 8, 11, 12, 15, 22, 23, 24],
 4: [9],
 5: [14, 6, 7, 22],
 6: [2, 3, 14, 16, 5, 22, 23],
 7: [14, 16, 5],
 8: [27, 12, 3, 23, 24],
 9: [0, 28, 4, 20],
 10: [26, 1, 28, 22],
 11: [3, 15, 24],
 12: [8, 3, 24],
 13: [25],
 14: [6, 7, 16, 5],
 15: [26, 28, 3, 20, 22, 11],
 16: [2, 14, 6, 7, 21],
 17: [0, 1, 18, 19],
 18: [25, 19, 17],
 19: [0, 18, 17],
 20: [28, 9, 15],
 21: [2, 16],
 22: [26, 3, 5, 6, 10, 15],
 23: [6, 8, 3],
 24: [27, 12, 3, 8, 11],
 25: [18, 13],
 26: [28, 10, 22, 15],
 27: [8, 24],
 28: [0, 26, 1, 15, 20, 9, 10]}

In [ ]:
yesyes = np.zeros((29,29))
yes = new_neighbors
for i in yes:
  for j in yes[i]:
    yesyes[i][j] = dist[i][j]

In [ ]:
def standard(array):
  for i,j in enumerate(array):
    array[i] = j/sum(j)
  return array

In [ ]:
final = standard(yesyes)

# **Uji Moran**

$I = \frac{n}{W} \cdot \frac{\sum_i \sum_j w_{ij} (x_i - \bar{x})(x_j - \bar{x})}{\sum_i (x_i - \bar{x})^2}$

In [ ]:
W_array = final.copy().astype(float)
y = df_no_outliers['Y'].values

neighbors = {i: np.where(W_array[i] > 0)[0].tolist() for i in range(W_array.shape[0])}
weights = {i: W_array[i, W_array[i] > 0].tolist() for i in range(W_array.shape[0])}

w = W(neighbors, weights)
w.transform = "R"

moran = Moran(y, w, permutations=999)

print("Moran’s I:", moran.I)
print("Expected I:", moran.EI)
print("Z-score:", moran.z_sim)
print("P-value:", moran.p_sim)

Moran’s I: 0.13716075653230575
Expected I: -0.03571428571428571
Z-score: 1.2840211857633
P-value: 0.104

In [ ]:
W = final.copy().astype(float)

In [ ]:
y = df_no_outliers['Y']
X = df_no_outliers[['RLS', 'AHH', 'TPT', 'APD']].copy()

In [ ]:
WX_RLS = W.dot(df_no_outliers['RLS'])
WX_AHH = W.dot(df_no_outliers['AHH'])
WX_TPT = W.dot(df_no_outliers['TPT'])
WX_APD = W.dot(df_no_outliers['APD'])

In [ ]:
X.loc[:, 'WX_RLS'] = WX_RLS
X.loc[:, 'WX_AHH'] = WX_AHH
X.loc[:, 'WX_TPT'] = WX_TPT
X.loc[:, 'WX_APD'] = WX_APD

In [ ]:
X = sm.add_constant(X)

In [ ]:
model = sm.OLS(y, X).fit()

In [ ]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.360
Model:                            OLS   Adj. R-squared:                  0.104
Method:                 Least Squares   F-statistic:                     1.407
Date:                Thu, 06 Nov 2025   Prob (F-statistic):              0.253
Time:                        08:11:09   Log-Likelihood:                -63.732
No. Observations:                  29   AIC:                             145.5
Df Residuals:                      20   BIC:                             157.8
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         81.5093    106.525      0.765      0.453    -140.697     303.716
RLS           -0.7859      0.856     -0.919      0.369      -2.570       0.999
AHH           -0.9951      0.739     -1.347      0.193      -2.537       0.546
TPT            0.2770      0.623      0.445      0.661      -1.023       1.577
APD           -0.0008      0.002     -0.522      0.607      -0.004       0.002
WX_RLS         0.4477      1.993      0.225      0.825      -3.709       4.604
WX_AHH         0.0368      1.172      0.031      0.975      -2.409       2.482
WX_TPT        -1.3064      1.061     -1.232      0.232      -3.519       0.906
WX_APD         0.0043      0.003      1.617      0.122      -0.001       0.010
==============================================================================
Omnibus:                        0.610   Durbin-Watson:                   1.771
Prob(Omnibus):                  0.737   Jarque-Bera (JB):                0.695
Skew:                           0.190   Prob(JB):                        0.706
Kurtosis:                       2.344   Cond. No.                     7.72e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.72e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
residuals = model.resid
resid_standardized = (residuals - np.mean(residuals)) / np.std(residuals)

stat, p = kstest(resid_standardized, 'norm')
print(f"KS Statistic = {stat:.3f}, p-value = {p:.3f}")

KS Statistic = 0.103, p-value = 0.885

# **VIF**

In [ ]:
vif_data = pd.DataFrame({
    "Variable": X.columns,
    "VIF": [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
})
print(vif_data)

  Variable           VIF
0    const  47813.309871
1      RLS      3.195924
2      AHH      5.213996
3      TPT      3.091498
4      APD      2.034126
5   WX_RLS      6.264719
6   WX_AHH     10.518175
7   WX_TPT      5.091233
8   WX_APD      1.342740